// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7CDPzUMlcj4qzc18vwp6WrKcukmsi-c',
    appId: '1:118636212101:web:c029e676e1102b36f45eec',
    messagingSenderId: '118636212101',
    projectId: 'notey-e21c9',
    authDomain: 'notey-e21c9.firebaseapp.com',
    storageBucket: 'notey-e21c9.appspot.com',
    measurementId: 'G-PN8Z5FRR66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXho4ncTokm82dBk1kEN6ax2PdLQ1Icw',
    appId: '1:118636212101:android:26546bed228f4621f45eec',
    messagingSenderId: '118636212101',
    projectId: 'notey-e21c9',
    storageBucket: 'notey-e21c9.appspot.com',
  );
}
